services:
  postgres:
    image: postgres:16.11-bookworm
    restart: always
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-blogapi}
      - POSTGRES_USER=${POSTGRES_USER:-blogapi}
      - POSTGRES_DB=blogapispring
    profiles:
      - postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER:-blogapi}", "-d", "blogapispring" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data: